### ISSUE TITLE
Not sure what they changed with MD but all my numbers are banned

### ISSUE THREAD

**Issue by xbassols** [tulir/whatsmeow#11]
We used whatsapp-go internally for alerts in my company and was working well. Yesterday we moved to whastmeow and all our numbers got banned in a matter of seconds. There is something definitely tipping them out.

**Comment by beshoo** [comment]
Are you sure it is banned or you lost a session?
banned mean you can not use WhatsApp anymore!

Are you running the "whatsmeow" on a server or on your localhost, I mean the IP address of the connection is a hosting server or your home IP address?

**Comment by xbassols** [comment]
I'm sure its banned. The app says so when I try to re-verify the number. The IP I use is indeed a GCP IP and that could be the problem.

**Comment by beshoo** [comment]
Oh, sorry for your loss...
Well, I've talked about this before. Whatsapp will suspend any number that uses non-residential IP addresses. Because WhatsApp will indicate that you are using some kind of bot!

Before, we were using device communication (server sends the message via socket to your device and your WhatsApp will send the message to the recipient which means WhatsApp Servers will see a legitimate message sent from the app). to send the message. 

But in your case, the IP used is Google Cloud since you are using multiple devices.

It's a big problem but you can fix it if you use a proxy that uses your home connection.
Or use your home computer to run whatsmeow!

**Comment by tulir** [comment]
Are you using virtual (voip) numbers or something similarly suspicious? They've probably made their anti-spam detection stricter, but I didn't get banned at any point during development and testing, so I don't think they're banning just for using this.

**Comment by beshoo** [comment]
It is related to the ip address, am 100% sure.

Regard
