### ISSUE TITLE
Error in some messages

### ISSUE THREAD

**Issue by ferd1995** [tulir/whatsmeow#235]
Some messages are not sent, because the log reports the following message

```
11:04:52.991[31m [Database ERROR] Failed to handle retry receipt for XXXXX@s.whatsapp.net/3EB00EB42154532069B4 from XXXXX@s.whatsapp.net: couldn't find message 3EB00EB42154532069B4[0m
```

Any idea?

**Comment by Serenity-77** [comment]
Whatsmeow seems to cache the message before send to facilitate message retry in the future.

This maybe happen after you send a message and then restarted the connection, this will cause all previously cached message lost.

So before you send the message (`waProto *Message`) you need to store the message in persistent storage, so that if there is a retry request come you can fetch from it using `client.GetMessageForRetry` function field
