### ISSUE TITLE
Is it production ready? Is this ready for a SaaS product?

### ISSUE THREAD

**Issue by ezesculli** [tulir/whatsmeow#293]
Hi, I would like to know:
- Are there SaaS companies using this? Have they faced any issues?
- Any big company using it on a big scale? (>1000 instances)
- Any notice or information about WhatsApp limiting this in the future? Or banning WhatsApp numbers using this API?
- Any limitations or known issues that come when you're using this at scale?

Thanks in advance!

**Comment by Paguiar735** [comment]
> Hi, I would like to know:
> - Are there SaaS companies using this? Have they faced any issues?
> - Any big company using it on a big scale? (>1000 instances)
> - Any notice or information about WhatsApp limiting this in the future? Or banning WhatsApp numbers using this API?
> - Any limitations or known issues that come when you're using this at scale?
> 
> Thanks in advance!

Given the project's MPL-licensed, ie. it in short allows you to keep your source code private, alongside the fact that WhatsApp's averse to any type of automation that it considers to be "Harm[ful] to WhatsApp or Our Users" in its platform, unless it's coming from an official WhatsApp Businesses API partner [1], we can't stress enough that the project's not intended to be used as a SaaS or at scale since that would be against WhatsApp's ToS [2], so expect retaliation from Meta if you don't abide by the ToS you agreed to upon joining WhatsApp: having your WhatsApp account banned, your public IP blacklisted and more.

If you're the spokesperson for a business that plans to integrate WhatsApp into their workflow, you should reach out to an official WhatsApp Business API partner [1] and they'll walk you through a strict Meta application process so you can obtain a WhatsApp Business API key. Once you have it, they'll build a tailored solution – or provide you with low-end tool to do it yourself – you agreed to upon closing a deal with them.

None of this should be a problem for businesses, because if they plan to use it at scale then they surely have the time and money to undergo this process and can definitely afford the costs associated with holding a WhatsApp Businesses API key.

By the way, be wary of whoever claims to be partners with Meta or its platforms: unless they're listed in any of the official Meta Businesses Partners Repository [2], they're lying.

[1] https://www.facebook.com/business/partner-directory
[2] https://www.whatsapp.com/legal/terms-of-service/?lang=en
