### ISSUE TITLE
Force Update Keys

### ISSUE THREAD

**Issue by fcerd95** [tulir/whatsmeow#72]
Any way to force to update users keys?

Some users dont received the message correct, because keys is outdated.

Exemple:
1) User send message to bot
2) User reinstall whatsapp
3) Bot send message to user (Here is outdated user key)

**Comment by tulir** [comment]
It updates keys automatically.

4. User's device sends retry receipt because it failed to decrypt the message
5. Bot detects keys changed and encrypts message for new keys
   * This part only works if it hasn't been restarted after the message was sent. If you want it to work across restarts, you'll need to store the messages and implement the `GetMessageForRetry` function.
