### ISSUE TITLE
Response to specific message

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#88]
Is there a way to reply for a specific message, same like the case in the WhatsApp app, where we hold a specific message and reply to it. Thanks

**Comment by tulir** [comment]
`StanzaId` (which message ID are you replying to), `Participant` (JID of user who sent that message) and optionally `QuotedMessage` (the content of that message) inside `ContextInfo`. Requires using `ExtendedTextMessage` for text messages.

(`QuotedMessage` is optional because other users' whatsapp clients won't trust it anyway. If you omit it, your own clients will show a blank quote, but everyone else will see it correctly as long as `StanzaId` and `Participant` are correct)

**Comment by deven96** [comment]
Could there be a small example of how to add this? I'm a bit torn
